apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./service-account.yaml

configMapGenerator:
- name: logstash
  files:
  - ./config/logstash-values.yaml
- name: monitoring
  files:
  - ./config/kube-state-metrics.yaml
  - ./config/prometheus.yaml
  - ./config/cost-model.yaml
  - ./config/node-exporter.yaml
  - ./config/filebeat.yaml
- name: filebeat
  files:
  - ./config/filebeat-config.yaml
  - ./config/filebeat-seed-data.txt.bz2

generatorOptions:
  disableNameSuffixHash: true
