name: Main workflow
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest
    env:
      BUILD_METADATA: build.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Set up Docker
        run: |
          ./hack/install-docker-for-mac.sh
          docker version
      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Go Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-gobuildcache-${{ hashFiles('**.go') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcache-
      - name: Set up Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: redskyops
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.BMASTERS_PRIVATE_KEY }}
      - name: Bootstrap
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ -z "${GITHUB_REF/refs\/tags\/*/}" ]; then
            TAG=${GITHUB_REF##*/v}
            echo "::set-env name=DOCKER_TAG::latest"
            echo "::set-env name=VERSION::v${TAG}"
            echo "::set-env name=IMG::redskyops/redskyops-controller:${TAG}"
            echo "::set-env name=REDSKYCTL_IMG::redskyops/redskyctl:${TAG}"
            echo "::set-env name=SETUPTOOLS_IMG::redskyops/setuptools:${TAG}"
            echo "::set-env name=AC_USERNAME::${{ secrets.AC_USERNAME }}"
            printenv DOCKER_PASSWORD | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          else
            TAG="sha-$(git rev-parse --short HEAD)"
            echo "::set-env name=DOCKER_TAG::canary" # TODO This should change to "latest" after the 1.6.0 release
            echo "::set-env name=IMG::gcr.io/redskyops/redskyops-controller:${TAG}"
            echo "::set-env name=REDSKYCTL_IMG::gcr.io/redskyops/redskyctl:${TAG}"
            echo "::set-env name=SETUPTOOLS_IMG::gcr.io/redskyops/setuptools:${TAG}"
            gcloud --quiet auth configure-docker
          fi
          echo "::set-env name=PULL_POLICY::Always"
      - name: Build controller
        run: |
          make docker-build-ci
      - name: Build tool
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --release-notes hack/changelog.md.txt
        env:
          GITHUB_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          AC_IDENTITY_P12: ${{ secrets.AC_IDENTITY_P12 }}
      - name: Push Docker images
        run: |
          docker tag "${IMG}" "${IMG%%:*}:${DOCKER_TAG}"
          docker tag "${REDSKYCTL_IMG}" "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker tag "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
          make docker-push
          docker push "${IMG%%:*}:${DOCKER_TAG}"
          docker push "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker push "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
      - name: Upload macOS binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_darwin_amd64
          path: dist/redskyctl-darwin-amd64.tar.gz
      - name: Upload Linux binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_linux_amd64
          path: dist/redskyctl-linux-amd64.tar.gz
