name: Pull Request workflow
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Verify License Header
        uses: talos-systems/conform@v0.1.0-alpha.19
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Go Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-gotestcache-${{ hashFiles('**.go') }}
          restore-keys: |
            ${{ runner.os }}-gotestcache-
      - name: Run tests
        run: |
          hack/install_kustomize.sh
          make test
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: pr.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      # Launch KinD early so we can do other things while the control plane converges
      - name: KinD (Kubernetes in Docker) Initialization
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          wait: 0s
      - name: Set up Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      - name: Bootstrap
        run: |
          TAG="sha-$(git rev-parse --short HEAD)"
          echo "::set-env name=IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyops-controller:${TAG}"
          echo "::set-env name=REDSKYCTL_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyctl:${TAG}"
          echo "::set-env name=SETUPTOOLS_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/setuptools:${TAG}"
          echo "::set-env name=PULL_POLICY::Always"
          echo "::set-env name=DOCKER_TAG::pr-${{ github.event.number }}"
          gcloud --quiet auth configure-docker
      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Go Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-gobuildcache-${{ hashFiles('**.go') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcache-
      - name: Build controller
        run: |
          hack/install_kustomize.sh
          make docker-build-ci
      - name: Build tool
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --skip-sign --rm-dist
      - name: Push Docker images
        run: |
          docker tag "${IMG}" "${IMG%%:*}:${DOCKER_TAG}"
          docker tag "${REDSKYCTL_IMG}" "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker tag "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
          make docker-push
          docker push "${IMG%%:*}:${DOCKER_TAG}"
          docker push "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker push "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: redskyctl_darwin_amd64
          path: dist/redskyctl-darwin-amd64.tar.gz
      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: redskyctl_linux_amd64
          path: dist/redskyctl-linux-amd64.tar.gz
      - name: redsky quickstart
        run: |
          hack/integration.sh
